version: '2.1'

services:
  eureka-server:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'proyectofinal-network'
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "444:444"
    networks:
      - 'proyectofinal-network'
  cart-service:
    build: cart-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - 'proyectofinal-network'
  products-service:
    build: products-service
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - 'proyectofinal-network'
  sale-service:
    build: sale-service
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - 'proyectofinal-network'

networks:
  proyectofinal-network: