version: '2.1'

services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server:1.0.0
    build:
      context: ./eureka-sv
    ports:
      - "8761:8761"
    restart: always
    networks:
      - "integrador-network"
  api-gateway:
    container_name: api-gateway
    image: api-gateway:1.0.0
    build:
      context: ./api-gateway
    ports:
      - "444:444"
    networks:
      - "integrador-network"
    restart: always
  products-service:
    container_name: products-service
    image: products-service:1.0.0
    build:
      context: ./products-service
    ports:
      - "8081:8081"
    networks:
      - "integrador-network"
    environment:
      - DATABASE_URL=jdbc:mysql://integrador_db:3306/sv_products?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=181222root
    restart: always
    depends_on:
      - integrador_db
  cart-service:
    container_name: cart-service
    image: cart-service:1.0.0
    build:
      context: ./cart-service
    ports:
      - "8082:8082"
    networks:
      - "integrador-network"
    environment:
      - DATABASE_URL=jdbc:mysql://integrador_db:3306/sv_carts?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=181222root
    restart: always
    depends_on:
      - integrador_db
  sale-service:
    container_name: sale-service
    image: sale-service:1.0.0
    build:
      context: ./sale-service
    ports:
      - "8083:8083"
    networks:
      - "integrador-network"
    environment:
      - DATABASE_URL=jdbc:mysql://integrador_db:3306/sv_sales?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=181222root
    restart: always
    depends_on:
      - integrador_db
  integrador_db:
    container_name: integrador_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - "integrador-network"
    volumes:
      - integrador_db_data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=181222root
      - MYSQL_ROOT_PASSWORD=181222root

volumes:
  integrador_db_data:

networks:
    integrador-network: